services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 445:445 # samba
      - 3001:3001 # clipboard
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 9696:9696 # prowlarr
      - 3000:3000 # whats-my-ip
      - 8191:8191 # flaresolverr
      - 8265:8265 # tdarr
      # qbittorrent 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp
      # jellyfin
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ./.docker-compose-storage/gluetun:/gluetun
    environment:
      # https://github.com/qdm12/gluetun-wiki/tree/main/setup/providers
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - SERVER_COUNTRIES=United States
      - UPDATER_PERIOD=24h

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/sonarr/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/tv:/tv
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/radarr/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/movies:/movies
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./.docker-compose-storage/qbitorrent/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/jellyfin/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/tv:/data/tvshows
      - ./.docker-compose-storage/qbitorrent/downloads/movies:/data/movies
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      
  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./.docker-compose-storage/prowlarr/config:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  whats-my-ip:
    image: 00000vish/docker-whats-my-ip:latest
    container_name: whats-my-ip
    environment:
      - PORT=3000
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      
  docker-samba:
    image: 00000vish/docker-samba:latest
    container_name: docker-samba
    environment:
      - USERNAME=CHANGE-ME
      - PASSWORD=CHANGE-ME
    volumes:
      - ./storage:/storage
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  docker-clipboard:
    image: 00000vish/docker-clipboard:latest
    container_name: docker-clipboard
    environment:
      - PORT=3001
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=true
      - inContainer=true
      - ffmpegVersion=6
      - nodeName=server

    volumes:
      - ./.docker-compose-storage/tdarr/server:/app/server
      - ./.docker-compose-storage/tdarr/configs:/app/configs
      - ./.docker-compose-storage/tdarr/logs:/app/logs
      - ./.docker-compose-storage/tdarr/transcode_cache:/temp
      - ./.docker-compose-storage/qbitorrent/downloads/tv:/media/tvshows
      - ./.docker-compose-storage/qbitorrent/downloads/movies:/media/movies
    network_mode: service:gluetun
    depends_on:
      - gluetun
    devices:
      - /dev/dri:/dev/dri
