services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8989:8989 # sonarr
      - 7878:7878 # radarr
      - 9117:9117 # jackett
      - 9696:9696 # prowlarr
      - 3000:3000 # whats-my-ip
      # qbittorrent 
      - 8080:8080 
      - 6881:6881 
      - 6881:6881/udp
      # jellyfin
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    volumes:
      - ./.docker-compose-storage/gluetun:/gluetun
    environment:
      # https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - UPDATER_PERIOD=24h
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/sonarr/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/tv:/tv
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent
      - jackett
      
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/radarr/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/movies:/movies
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
      - qbittorrent
      - jackett
  
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - ./.docker-compose-storage/qbitorrent/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
  
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./.docker-compose-storage/jellyfin/config:/config
      - ./.docker-compose-storage/qbitorrent/downloads/tv:/data/tvshows
      - ./.docker-compose-storage/qbitorrent/downloads/movies:/data/movies
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - ./.docker-compose-storage/jackett/config:/config
      - ./.docker-compose-storage/jackett/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./.docker-compose-storage/prowlarr/config:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
  
  whats-my-ip:
    image: 00000vish/docker-whats-my-ip:latest
    container_name: whats-my-ip
    environment:
      - PORT=3000
    ports:
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
